### ISSUE TITLE
Wrong type for isEnabled in TradeSymbol interface

### ISSUE THREAD

**Issue by oakify** [zishe/iex-cloud#33]
- **I'm submitting a ...**
    [x] bug report
    [ ] feature request
    [ ] question about the decisions made in the repository
    [ ] question about how to use this project

- **Summary**
The type of **isEnabled** in **TradeSymbol** should be `boolean` instead of `string` as per the official doc.
File: https://github.com/zishe/iex-cloud/blob/develop/src/endpoints/reference-data/Symbols.ts

Official doc: https://iexcloud.io/docs/api/#symbols

```
  {
    "symbol": "A",
    "name": "Agilent Technologies Inc.",
    "date": "2019-03-07",
    "type": "cs",
    "iexId": "IEX_46574843354B2D52",
    "region": "US",
    "currency": "USD",
    "isEnabled": true,
    "figi": "BBG000C2V3D6",
    "cik": "1090872",
  },

```

**Comment by chatman-media** [comment]
Done, thanks!
